#ifndef __VERSION_H
#define __VERSION_H

#define VERSION_MAJOR 1
#define VERSION_MINOR 1
#define VERSION_BUILD_ID "20130729-203440"
#define PRODUCT_NAME "EHZ, SO, MODBUS COUNTER"

#endif /* end __VERSION_H */
