#ifndef __VERSION_H
#define __VERSION_H

#define VERSION_MAJOR 1
#define VERSION_MINOR 3
#define VERSION_BUILD_ID "20121130-213438"
#define PRODUCT_NAME "EHZ, SO, MODBUS COUNTER"


#endif /* end __VERSION_H */
